config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    resources :comments
  end

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      get "/events" => "events#index", :as => :events
      get "/events/:event_id" => "events#show", :as => :event
      get "/comments/:comment_id" => "comments#show", :as => :comment
      post "/comments" => "comments#create", :as => :create_comments
      delete "/comments/:comment_id" => "comments#destroy", :as => :delete_comment
      post "/signup" => "auth#signup"
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
    end
  end
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :name
  belongs_to :event
  belongs_to :user, :optional => true
end

app/models/event.rb
class Event < ApplicationRecord

  validates_presence_of :title
  belongs_to :user, :optional => true
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
  has_many :comments

  before_create :generate_authentication_token

  def generate_authentication_token
    self.authentication_token = Devise.friendly_token
  end

end

app/controllers/api/v1/auth_controller.rb
class Api::V1::AuthController < ApiController

  before_action :authenticate_user!, :only => [:logout]

  def signup
    user = User.new( :email => params[:email], :password => params[:password] )

    if user.save
      render :json => { :user_id => user.id }
    else
      render :json => { :message => "Failed", :errors => user.errors }, :status => 400
    end
  end

  def login
    if params[:email] && params[:password]
      user = User.find_by_email( params[:email] )
    end

    if user && user.valid_password?( params[:password] )
      render :json => { :message => "Ok",
                         :auth_token => user.authentication_token,
                         :user_id => user.id }
    else
      render :json => { :message => "Email or Password is wrong" }, :status => 401
    end
  end

  def logout
    current_user.generate_authentication_token # 重新产生一组，本来的 token 就失效了
    current_user.save!

    render :json => { :message => "Ok"}
  end

end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApiController

  def create
    @event = Event.find(params[:event_id])
    @comment = Comment.new(:event_id => @event.id,
                           :name => params[:name],
                           :body => params[:body])
    @comment.user = current_user
    if @comment.save
      render :json => {
        :comment_url => api_v1_comment_url(@comment.id)
      }
    else
      render :json => { :message => "发表评论失败", :errors => @comment.errors }, :status => 400
    end
  end

  def show
    @comment = Comment.find(params[:comment_id])

    render :json => {
      :name => @comment.name,
      :body => @comment.body
    }
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    @comment.destroy

    render :json => {:message => "已删除评论"}
  end

end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApiController

  def index
    @events = Event.all
    render :json => {
      :data => @events.map { |event|
        {:title => event.title,
          :description => event.description,
          :event_url => api_v1_event_url(event.id)
        }
      }
    }
  end

  def show
    @event = Event.find(params[:event_id])

    render :json => {
      :title => @event.title,
      :description => @event.description,
      :detail => @event.detail
    }
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base

  before_action :authenticate_user_from_token!

  def authenticate_user_from_token!
    if params[:auth_token].present?
      user = User.find_by_authentication_token(params[:auth_token])

      sign_in(user, store: false) if user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :find_event

  def create
    @comment = @event.comments.new(params[:comment].permit(:name, :body))
    @comment.user = current_user
    if @comment.save
      redirect_to event_path(@event)
    else
      redirect_to event_path(@event), alert: "未发表成功"
    end
  end

  def destroy
    @comment = @event.comments.find(params[:id])
    @comment.destroy
    redirect_to event_path(@event)
  end

  protected

  def find_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to events_path, alert: "添加活动成功"
    else
      render :new
    end
  end

  def update
    @event = Event.find(params[:id])
    if !current_user = @event.user
      redirect_to events_path, alert: "你没有修改的权限"
    else
      if @event.update(event_params)
        redirect_to events_path, alert: "编辑活动成功"
      else
        render :edit
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if !current_user = @event.user
      redirect_to events_path, alert: "你没有修改的权限"
    else
      @event.destroy
      redirect_to events_path
    end
  end

  protected

  def event_params
    params.require(:event).permit(:title, :description, :user_id, :detail)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/api/v1/auth_helper.rb
module Api::V1::AuthHelper
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/api/v1/events_helper.rb
module Api::V1::EventsHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <div class="form-group">
    <%= f.input :title, :label => "名称", input_html: {class: "form-control"} %>
    <%= f.input :description, :label => "简介", input_html: {class: "form-control"}%>
    <%= f.input :detail, :label => "内容", as: :text, input_html: { :rows => 15}%>
  </div>
  <%= f.submit "提交", class: "btn btn-primary", data: { disable_with: "提交中。。。"} %>
<% end %>

app/views/events/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>编辑活动</h1>
  <hr>
  <%= render :partial => "form", :local => {:event => @event} %>
</div>

app/views/events/index.html.erb
<div class="col-md-10 col-md-offset-1">
  <h1>活动列表</h1>

  <% if current_user %>
    <p>已经登入：你的 API token 是 <code><%= current_user.authentication_token  %></code></p>
  <% else %>
    <p>尚未登入</p>
  <% end %>

  <div class="pull-right">
    <%= link_to("添加新活动", new_event_path, class: "btn btn-primary") %>
  </div>

  <table class="table table-border">
    <tr>
      <th>列表</th>
      <th>活动名</th>
      <th>发布者</th>
      <th>简介</th>
      <th>管理</th>
    </tr>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td>#</td>
          <td><%= link_to(event.title, event_path(event)) %></td>
          <td><%= event.user.email %></td>
          <td><%= event.description %></td>
          <td>
            <% if current_user == event.user %>
              <%= link_to("编辑", edit_event_path(event), class: "btn btn-sm btn-primary") %>
              <%= link_to("删除", event_path(event), :method => :delete, class: "btn btn-sm btn-primary", data: {confirm: "你确定要删除吗？"}) %>
            <% else %>
              你没有管理权限
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>添加新活动</h1>
  <hr>
  <%= render :partial => "form", :local => {:event => @event} %>
</div>

app/views/events/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2><%= @event.title %></h2>
  <hr>

  <p class="description">
    <h4>简介</h4><br>
    <%= @event.description %>
  </p>

  <p class="detail">
    <h4>活动内容</h4><br>
    <%= simple_format @event.detail %>
  </p>
  <hr>

  <div id="comments">
    <h3><%= @event.comments.count %> 条评论</h3>
    <% if @event.comments.count == 0 %>
      <p>尚未有人评论</p>
    <% else %>
      <% @floor = 1 %>
      <% @event.comments.each do |comment| %>
        <%= @floor %>楼
        <div class="comment clearfix">
          <div class="comment_content">
            <p class="comment_name"><strong><%= comment.name %></strong></p>
            <p class="comment_body"><%= comment.body %></p>
          </div>
          <div class="pull-right">
            <%= comment.user.email %>
            <% if current_user == comment.user %>
              <p><%= link_to("删除", event_comment_path(comment.event, comment), method: :delete, class: "button", data: {confirm: "你确定删除吗？"})%></p>
            <% end %>
          </div>
        </div>
        <% @floor = @floor + 1 %>
        </br>
        <hr>
      <% end %>
    <% end %>

    <h4>发表评论</h4>
    <%= simple_form_for ([@event, @event.comments.build]) do |f| %>
      <div class="form-group">
        <%= f.input :name, :label => "标题", input_html: {class: "form-control"} %><br>
        <%= f.input :body, :label => "内容", input_html: {class: "form-control"} %>
      </div>
      <br>
      <%= f.submit "提交", class: "btn btn-primary", data: { disable_with: "提交中。。。"} %>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Hello World</h1>